spring:
  datasource:
    url: jdbc:mysql://localhost/hospitallab4db?serverTimezone=UTC&useSSL=false
    username: root
    password: sashamerchukqwerty12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: validate
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8080